package codestory2013;

import nk.chemin.DecisionRoutage;
import nk.chemin.Parametre;

rule "PremiereQuestion"
when 
	$dr : DecisionRoutage(decide == false)
	Parametre(nom == "q", valeur == "Quelle est ton adresse email")
then
	$dr.resoudStatique("mail.txt");
	update($dr);
end

rule "Abonnement ML"
when
	$dr : DecisionRoutage(decide == false)
	Parametre(nom == "q", valeur == "Es tu abonne a la mailing list(OUI/NON)")
then
	$dr.resoudStatique("OUI.txt");
	update($dr);
end

rule "Bonheur"
when
	$dr : DecisionRoutage(decide == false)
	Parametre(nom == "q", valeur == "Es tu heureux de participer(OUI/NON)")
then
	$dr.resoudStatique("OUI.txt");
	update($dr);
end

rule "Question inconnue"
salience -1
when
	$dr : DecisionRoutage(decide == false)
	Parametre(nom == "q", valeur matches ".*\\(OUI/NON\\)")
then
	$dr.resoudStatique("NON.txt");
	update($dr);
end